package com.api.monitor.api.dto;

import java.time.LocalDateTime;

import com.api.monitor.entity.Incident;

public record IncidentResponse(
        Long id,
        String title,
        String description,
        String status,
        String startedAt,
        String resolvedAt,
        String failureReason,
        Long downtimeDurationMinutes,
        Boolean autoGenerated,
        Long endpointId
) {
    public static IncidentResponse fromEntity(Incident i) {
        return new IncidentResponse(
                i.getId(),
                i.getTitle(),
                i.getDescription(),
                i.getStatus() != null ? i.getStatus().name() : null,
                format(i.getStartedAt()),
                format(i.getResolvedAt()),
                i.getFailureReason(),
                i.getDowntimeDurationMinutes(),
                i.getAutoGenerated(),
                i.getEndpoint() != null ? i.getEndpoint().getId() : null
        );
    }

    private static String format(LocalDateTime t) {
        return t == null ? null : t.toString();
    }
}
