spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:missing}
            client-secret: ${GOOGLE_CLIENT_SECRET:missing}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

apiwatch:
  app:
    base-url: ${APIWATCH_BASE_URL:https://apiwatch.app}
  mail:
    enabled: ${APIWATCH_MAIL_ENABLED:true}
    from: ${APIWATCH_MAIL_FROM:no-reply@apiwatch.app}
    SMTP2GO_API_KEY: ${SMTP2GO_API_KEY:missing}
