/** Mirrors backend JSON for Phase 3–5 APIs. */

import type { EndpointRow, SslMonitorRow } from '@/types/dashboard.ts'

export type EndpointDetailPayload = {
  endpoint: EndpointRow
  checks: EndpointCheckDto[]
  uptimePct: string
  avgResponseMs: string
}

export type EndpointCheckDto = {
  id: number
  checkedAt: string | null
  responseTimeMs: number | null
  statusCode: number | null
  isUp: boolean | null
  errorMessage: string | null
}

export type IncidentDto = {
  id: number
  title: string
  description: string | null
  status: string | null
  startedAt: string | null
  resolvedAt: string | null
  failureReason: string | null
  downtimeDurationMinutes: number | null
  autoGenerated: boolean | null
  endpointId: number | null
}

export type UserSettingsDto = {
  id: number
  email: string
  name: string | null
  picture: string | null
  subscriptionTier: string
  statusSlug: string | null
  statusPageTitle: string | null
  statusPageLogoUrl: string | null
  notifyOnEndpointDown: boolean | null
  notifyOnEndpointRecovery: boolean | null
}

export type StatusSettingsDto = {
  statusSlug: string | null
  statusPageTitle: string | null
  statusPageLogoUrl: string | null
}

export type PublicStatusPayload = {
  slug: string
  pageTitle: string
  logoUrl: string | null
  overallStatusLabel: string
  statusKind: string
  endpoints: EndpointRow[]
  sslMonitors: SslMonitorRow[]
  incidents: IncidentDto[]
}
