package com.api.monitor.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "incidents")
public class Incident {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(nullable = false)
    private String title;

    @Column(length = 2000)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private IncidentStatus status = IncidentStatus.INVESTIGATING;

    @Column(name = "started_at", nullable = false)
    private LocalDateTime startedAt = LocalDateTime.now();

    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;

    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();

    /** For auto-incidents: which endpoint caused this. Null for manual/heartbeat incidents. */
    @ManyToOne
    @JoinColumn(name = "endpoint_id")
    private Endpoint endpoint;

    /** For heartbeat auto-incidents: which heartbeat monitor missed its ping. */
    @ManyToOne
    @JoinColumn(name = "heartbeat_monitor_id")
    private HeartbeatMonitor heartbeatMonitor;

    /** For SSL auto-incidents: which SSL monitor triggered this. */
    @ManyToOne
    @JoinColumn(name = "ssl_monitor_id")
    private SslMonitor sslMonitor;

    /** Auto-incident: e.g. "Timeout", "HTTP 5xx", "DNS failure", "Connection refused", "Heartbeat missed". */
    @Column(name = "failure_reason", length = 255)
    private String failureReason;

    /** Downtime duration in minutes (set when auto-resolved). */
    @Column(name = "downtime_duration_minutes")
    private Long downtimeDurationMinutes;

    /** True if created by monitoring; false if created by user. */
    @Column(name = "auto_generated", nullable = false)
    private Boolean autoGenerated = false;

    public enum IncidentStatus {
        INVESTIGATING,
        IDENTIFIED,
        MONITORING,
        RESOLVED
    }
}
